// Code generated by Kitex v0.3.4. DO NOT EDIT.

package bytegraphservice

import (
	"github.com/volcengine/vegraph-go-sdk/kitex_gen/bytegraph"
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return byteGraphServiceServiceInfo
}

var byteGraphServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ByteGraphService"
	handlerType := (*bytegraph.ByteGraphService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GremlinQuery": kitex.NewMethodInfo(gremlinQueryHandler, newByteGraphServiceGremlinQueryArgs, newByteGraphServiceGremlinQueryResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "bytegraph",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.4",
		Extra:           extra,
	}
	return svcInfo
}

func gremlinQueryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bytegraph.ByteGraphServiceGremlinQueryArgs)
	realResult := result.(*bytegraph.ByteGraphServiceGremlinQueryResult)
	success, err := handler.(bytegraph.ByteGraphService).GremlinQuery(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newByteGraphServiceGremlinQueryArgs() interface{} {
	return bytegraph.NewByteGraphServiceGremlinQueryArgs()
}

func newByteGraphServiceGremlinQueryResult() interface{} {
	return bytegraph.NewByteGraphServiceGremlinQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GremlinQuery(ctx context.Context, req *bytegraph.GremlinQueryRequest) (r *bytegraph.GremlinQueryResponse, err error) {
	var _args bytegraph.ByteGraphServiceGremlinQueryArgs
	_args.Req = req
	var _result bytegraph.ByteGraphServiceGremlinQueryResult
	if err = p.c.Call(ctx, "GremlinQuery", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
