// Code generated by Kitex v0.3.4. DO NOT EDIT.

package bytegraphservice

import (
	"github.com/volcengine/vegraph-go-sdk/kitex_gen/bytegraph"
	"github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler bytegraph.ByteGraphService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
